// apps/web/src/solid/studio/AssetShelf.tsx
import { createSignal, For, onCleanup, onMount, Show } from 'solid-js'
import { Portal } from 'solid-js/web'
import type { Asset } from './types'
import type { ProjectStore } from './useProject'

const ACCEPT =
  '.pdf,.png,.jpg,.jpeg,.webp,.gif,.avif,.svg,.mp4,.webm,.mov,.mkv,.mp3,.wav,.m4a,.aac,.ogg'
const GLYPH: Record<string, string> = { image: '▣', video: '▶', audio: '♪', pdf: '❐', other: '◇' },
  ORIGIN: Record<string, string> = {
    upload: 'yours',
    generated: 'made here',
    harvested: 'from the site',
  }
const size = (n: number) =>
  n >= 1e6 ? `${(n / 1e6).toFixed(1)} MB` : n >= 1e3 ? `${Math.round(n / 1e3)} KB` : `${n} B`
function Viewer(props: { store: ProjectStore; asset: Asset; close: () => void }) {
  const [busy, setBusy] = createSignal(false),
    [error, setError] = createSignal<string | null>(null),
    src = () => props.store.mediaUrl(props.asset.url)
  const key = (e: KeyboardEvent) => e.key === 'Escape' && props.close()
  onMount(() => window.addEventListener('keydown', key))
  onCleanup(() => window.removeEventListener('keydown', key))
  const reference = () => {
    props.store.addTarget({
      sceneId: null,
      tagName: 'asset',
      className: '',
      id: '',
      text: props.asset.name,
      selector: props.asset.path,
      asset: props.asset.path,
      assetOrigin: props.asset.origin,
    })
    props.close()
  }
  const remove = async () => {
    if (!confirm(`Delete ${props.asset.name}? This removes the file from the project.`)) return
    setBusy(true)
    setError(null)
    try {
      await props.store.deleteAsset(props.asset.path)
      props.close()
    } catch (e: any) {
      setError(e?.message ?? 'Could not delete it')
      setBusy(false)
    }
  }
  return (
    <Portal>
      <div class="lv-studio">
        <div class="asset-viewer" onClick={props.close}>
          <div class="asset-viewer-box" onClick={e => e.stopPropagation()}>
            <div class="asset-viewer-head">
              <span class="asset-viewer-name" title={props.asset.path}>
                {props.asset.name}
              </span>
              <span class="asset-viewer-meta">
                {props.asset.path} · {size(props.asset.size)}
              </span>
              <button class="asset-viewer-close" onClick={props.close}>
                ✕
              </button>
            </div>
            <div class="asset-viewer-body">
              <Show when={src()} fallback={<div class="asset-viewer-note">Loading…</div>}>
                {u => (
                  <Show
                    when={props.asset.kind === 'video'}
                    fallback={
                      <Show
                        when={props.asset.kind === 'audio'}
                        fallback={
                          <Show
                            when={props.asset.kind === 'image'}
                            fallback={
                              <Show
                                when={props.asset.kind === 'pdf'}
                                fallback={
                                  <div class="asset-viewer-note">
                                    Nothing to show for this kind of file.
                                  </div>
                                }
                              >
                                <iframe src={u()} title={props.asset.name} />
                              </Show>
                            }
                          >
                            <img src={u()} alt={props.asset.name} />
                          </Show>
                        }
                      >
                        <audio src={u()} controls autoplay />
                      </Show>
                    }
                  >
                    <video src={u()} controls autoplay preload="metadata" />
                  </Show>
                )}
              </Show>
            </div>
            <div class="asset-viewer-foot">
              <button class="viewer-btn primary" onClick={reference}>
                Use in chat
              </button>
              <Show when={src()}>
                {u => (
                  <a class="viewer-btn" href={u()} download={props.asset.name}>
                    Download
                  </a>
                )}
              </Show>
              <Show when={error()}>
                <span class="asset-viewer-error">{error()}</span>
              </Show>
              <button class="viewer-btn danger" disabled={busy()} onClick={() => void remove()}>
                {busy() ? 'Deleting…' : 'Delete'}
              </button>
            </div>
          </div>
        </div>
      </div>
    </Portal>
  )
}
function Card(props: { store: ProjectStore; asset: Asset; picked: boolean; open: () => void }) {
  const [failed, setFailed] = createSignal(false),
    thumb = () => props.store.mediaUrl(props.asset.thumbUrl)
  const reference = () =>
    props.store.addTarget({
      sceneId: null,
      tagName: 'asset',
      className: '',
      id: '',
      text: props.asset.name,
      selector: props.asset.path,
      asset: props.asset.path,
      assetOrigin: ORIGIN[props.asset.origin] ?? props.asset.origin,
    })
  return (
    <div class={`asset-card${props.picked ? ' picked' : ''}`}>
      <button
        class="asset-open"
        title={`${props.asset.path} · ${size(props.asset.size)} — click to open`}
        onClick={props.open}
      >
        <span class="asset-thumb">
          <Show
            when={thumb() && !failed()}
            fallback={<span class="asset-glyph">{GLYPH[props.asset.kind]}</span>}
          >
            <img src={thumb()!} alt="" draggable="false" onError={() => setFailed(true)} />
          </Show>
          <Show when={props.asset.kind === 'video' || props.asset.kind === 'audio'}>
            <span class="asset-play">▶</span>
          </Show>
        </span>
        <span class="asset-lines">
          <span class="asset-name">{props.asset.name}</span>
          <span class="asset-meta">{ORIGIN[props.asset.origin] ?? props.asset.origin}</span>
        </span>
      </button>
      <button
        class="asset-ref"
        title={props.picked ? 'Already referenced' : 'Reference this file in your next message'}
        onClick={reference}
      >
        {props.picked ? '✓' : '+'}
      </button>
    </div>
  )
}
export function AssetShelf(props: { store: ProjectStore }) {
  const [dragging, setDragging] = createSignal(false),
    [adding, setAdding] = createSignal(false),
    [error, setError] = createSignal<string | null>(null),
    [open, setOpen] = createSignal<Asset | null>(null)
  let input: HTMLInputElement | undefined,
    depth = 0
  const chosen = () => new Set(props.store.targets.map(t => t.asset).filter(Boolean))
  const add = async (files: FileList | File[] | null) => {
    if (!files) return
    setAdding(true)
    setError(null)
    try {
      await props.store.addAssets(files)
    } catch (e: any) {
      setError(e?.message ?? 'Could not add those files')
    } finally {
      setAdding(false)
      if (input) input.value = ''
    }
  }
  return (
    <div
      class={`timeline asset-shelf${dragging() ? ' dropping' : ''}`}
      onDragEnter={e => {
        if (!e.dataTransfer?.types.includes('Files')) return
        depth++
        setDragging(true)
      }}
      onDragOver={e => e.dataTransfer?.types.includes('Files') && e.preventDefault()}
      onDragLeave={() => {
        depth = Math.max(0, depth - 1)
        if (!depth) setDragging(false)
      }}
      onDrop={e => {
        if (!e.dataTransfer?.files.length) return
        e.preventDefault()
        depth = 0
        setDragging(false)
        void add(e.dataTransfer.files)
      }}
    >
      <div class="timeline-header">
        <h2>Assets</h2>
        <span class="timeline-meta">
          {props.store.assets.length
            ? `${props.store.assets.length} file${props.store.assets.length === 1 ? '' : 's'} · click to open, + to reference`
            : 'files this project can use'}
        </span>
        <input
          ref={input}
          type="file"
          hidden
          multiple
          accept={ACCEPT}
          onChange={e => void add(e.currentTarget.files)}
        />
        <button class="asset-add" disabled={adding()} onClick={() => input?.click()}>
          {adding() ? 'Adding…' : '+ Add'}
        </button>
      </div>
      <Show when={error()}>
        <div class="timeline-empty asset-error">{error()}</div>
      </Show>
      <Show
        when={props.store.assets.length}
        fallback={
          <div class="timeline-empty">
            Nothing yet. Drop files here — or ask for something, and what gets made lands here too.
          </div>
        }
      >
        <div class="strip">
          <For each={props.store.assets}>
            {a => (
              <Card
                store={props.store}
                asset={a}
                picked={chosen().has(a.path)}
                open={() => setOpen(a)}
              />
            )}
          </For>
        </div>
      </Show>
      <Show when={open()} keyed>
        {a => <Viewer store={props.store} asset={a} close={() => setOpen(null)} />}
      </Show>
    </div>
  )
}
export { Viewer as AssetViewer }

// apps/studio-web/src/studio/AssetShelf.tsx
/**
 * The shelf — what the project has to work WITH.
 *
 * The stage shows the artifact. This shows the material: the file the user
 * dropped, the logo recon harvested, the clip the agent generated, anything
 * added mid-session. It sits under the stage next to the scene strip because
 * it answers the same kind of question — which thing do you mean?
 *
 * Clicking an asset is the same act as clicking an element or dragging a range
 * on the video track: it becomes a `[n]` chip in the composer. The chip's
 * value is the WORKSPACE-RELATIVE PATH, which is exactly what the agent's
 * tools take, so "use [1] as the first frame" needs no lookup in between.
 */
import { useRef, useState } from 'react'
import type { Asset } from './client'
import type { ProjectStore } from './useProject'

const ACCEPT =
  '.pdf,.png,.jpg,.jpeg,.webp,.gif,.avif,.svg,.mp4,.webm,.mov,.mkv,.mp3,.wav,.m4a,.aac,.ogg'

const KIND_GLYPH: Record<string, string> = {
  image: '▣',
  video: '▶',
  audio: '♪',
  pdf: '❐',
  other: '◇',
}

/** Where it came from, in the fewest words that still distinguish them. */
const ORIGIN_LABEL: Record<string, string> = {
  upload: 'yours',
  generated: 'made here',
  harvested: 'from the site',
}

function size(bytes: number): string {
  if (bytes >= 1e6) return `${(bytes / 1e6).toFixed(1)} MB`
  if (bytes >= 1e3) return `${Math.round(bytes / 1e3)} KB`
  return `${bytes} B`
}

function AssetCard({
  store,
  asset,
  picked,
}: {
  store: ProjectStore
  asset: Asset
  picked: boolean
}) {
  const [failed, setFailed] = useState(false)
  const src = store.mediaUrl(asset.url)
  const showImage = asset.kind === 'image' && src && !failed

  return (
    <button
      type="button"
      className={`asset-card${picked ? ' picked' : ''}`}
      title={`${asset.path} · ${size(asset.size)}`}
      onClick={() =>
        store.addTarget({
          sceneId: null,
          tagName: 'asset',
          className: '',
          id: '',
          text: asset.name,
          selector: asset.path,
          asset: asset.path,
          assetOrigin: ORIGIN_LABEL[asset.origin] ?? asset.origin,
        })
      }
    >
      <span className="asset-thumb">
        {showImage ? (
          <img src={src} alt="" draggable={false} onError={() => setFailed(true)} />
        ) : (
          <span className="asset-glyph">{KIND_GLYPH[asset.kind] ?? KIND_GLYPH.other}</span>
        )}
      </span>
      <span className="asset-name">{asset.name}</span>
      <span className="asset-meta">{ORIGIN_LABEL[asset.origin] ?? asset.origin}</span>
    </button>
  )
}

export function AssetShelf({ store }: { store: ProjectStore }) {
  const s = store
  const [dragging, setDragging] = useState(false)
  const [adding, setAdding] = useState(false)
  const [error, setError] = useState<string | null>(null)
  const input = useRef<HTMLInputElement | null>(null)
  const depth = useRef(0)

  const chosen = new Set(s.targets.map(t => t.asset).filter(Boolean))

  const add = async (files: FileList | File[] | null) => {
    if (!files) return
    setAdding(true)
    setError(null)
    try {
      await s.addAssets(files)
    } catch (err: any) {
      setError(err?.message ?? 'Could not add those files')
    } finally {
      setAdding(false)
      if (input.current) input.current.value = ''
    }
  }

  return (
    // biome-ignore lint/a11y/noStaticElementInteractions: a drop zone is not a control
    <div
      className={`timeline asset-shelf${dragging ? ' dropping' : ''}`}
      onDragEnter={e => {
        if (!e.dataTransfer?.types.includes('Files')) return
        depth.current += 1
        setDragging(true)
      }}
      onDragOver={e => {
        if (e.dataTransfer?.types.includes('Files')) e.preventDefault()
      }}
      onDragLeave={() => {
        depth.current = Math.max(0, depth.current - 1)
        if (depth.current === 0) setDragging(false)
      }}
      onDrop={e => {
        if (!e.dataTransfer?.files.length) return
        e.preventDefault()
        depth.current = 0
        setDragging(false)
        void add(e.dataTransfer.files)
      }}
    >
      <div className="timeline-header">
        <h2>Assets</h2>
        <span className="timeline-meta">
          {s.assets.length > 0
            ? `${s.assets.length} file${s.assets.length === 1 ? '' : 's'} · click one to reference it`
            : 'files this project can use'}
        </span>
        <input
          ref={input}
          type="file"
          hidden
          multiple
          accept={ACCEPT}
          onChange={e => void add(e.target.files)}
        />
        <button
          type="button"
          className="asset-add"
          disabled={adding}
          onClick={() => input.current?.click()}
        >
          {adding ? 'Adding…' : '+ Add'}
        </button>
      </div>

      {error && <div className="timeline-empty asset-error">{error}</div>}

      {s.assets.length === 0 ? (
        <div className="timeline-empty">
          Nothing yet. Drop files here — or ask for something, and what gets made lands here too.
        </div>
      ) : (
        <div className="strip">
          {s.assets.map(asset => (
            <AssetCard key={asset.path} store={s} asset={asset} picked={chosen.has(asset.path)} />
          ))}
        </div>
      )}
    </div>
  )
}
