// apps/web/src/solid/studio/StudioView.tsx
import { Files, Link, MonitorPlay } from 'lucide-solid'
import {
  createEffect,
  createMemo,
  createSignal,
  For,
  Match,
  onCleanup,
  onMount,
  Show,
  Switch,
} from 'solid-js'
import { AssetShelf } from './AssetShelf'
import { Composer } from './Composer'
import { BrowserPreview } from './previews/BrowserPreview'
import { DeckPreview } from './previews/DeckPreview'
import { HtmlPreview } from './previews/HtmlPreview'
import { PdfPreview } from './previews/PdfPreview'
import { VideoPreview } from './previews/VideoPreview'
import { SceneStrip, SlideStrip } from './Strips'
import { Thread } from './Thread'
import { type ProjectStore, useProject } from './useProject'
import '../../studio/studio.css'
import './playback.css'

const TITLES: Record<string, string> = {
  html: 'Launch film',
  deck: 'Slide deck',
  video: 'Video',
  pdf: 'PDF',
  browser: 'Recording',
}
function Preview(props: { store: ProjectStore }) {
  const s = props.store
  const preview = () => s.project?.description.preview
  const kind = createMemo(() => preview()?.kind)
  const src = createMemo(() => {
    const value = preview()
    return value && 'url' in value ? s.previewUrl(value.url) : null
  })
  return (
    <Switch
      fallback={
        s.busy ? (
          <Build store={s} />
        ) : (
          <div class="building-stage">
            <div class="building-copy">
              <MonitorPlay size={20} />
              <div class="building-title">Nothing to preview yet</div>
              <div class="building-status">
                {s.project?.lastError
                  ? `Last attempt failed: ${s.project.lastError}. Ask the agent to try again.`
                  : 'Describe what you want in chat — the first result appears here as soon as it exists.'}
              </div>
            </div>
          </div>
        )
      }
    >
      <Match when={kind() === 'html' && !!src()}>
        <HtmlPreview store={s} src={src()!} />
      </Match>
      <Match when={kind() === 'deck' && !!src()}>
        <DeckPreview store={s} src={`${src()}&studio=1`} />
      </Match>
      <Match when={kind() === 'video' && !!src()}>
        <VideoPreview store={s} src={src()!} />
      </Match>
      <Match when={kind() === 'pdf' && !!src()}>
        <PdfPreview store={s} src={src()!} />
      </Match>
      <Match when={kind() === 'browser'}>
        <BrowserPreview store={s} profileId={(preview() as { profileId: string }).profileId} />
      </Match>
    </Switch>
  )
}
function Build(props: { store: ProjectStore }) {
  const shots = () => props.store.assets.filter(a => a.kind === 'image' && a.origin !== 'upload')
  return (
    <div class="build-process">
      <div class="build-process__stage">
        <Show when={shots()[0]} fallback={<MonitorPlay size={20} />} keyed>
          {a => <img src={props.store.mediaUrl(a.url, Date.parse(a.mtime)) ?? ''} alt={a.name} />}
        </Show>
        <div class="build-process__status">
          <span class="spinner" />
          <span>{props.store.status}</span>
        </div>
      </div>
      <div class="build-process__shots">
        <For each={shots().slice(1, 13)}>
          {a => (
            <img
              src={props.store.mediaUrl(a.thumbUrl ?? a.url, Date.parse(a.mtime)) ?? ''}
              alt={a.name}
            />
          )}
        </For>
      </div>
    </div>
  )
}
const RES = [
  { res: '720p', note: '1280 × 720 · 60 fps · quick share' },
  { res: '1080p', note: '1920 × 1080 · 60 fps · standard' },
  { res: '4k', note: '3840 × 2160 · 60 fps · slow render' },
]
function Actions(props: { store: ProjectStore }) {
  const s = props.store,
    [open, setOpen] = createSignal(false),
    [sharing, setSharing] = createSignal(false)
  let wrap: HTMLDivElement | undefined
  const launch = () => s.project?.description.preview?.kind === 'html',
    outputs = () =>
      [
        ...(s.project?.outputs ?? []),
        ...(s.project?.description.outputs ?? []).filter(
          x => !(s.project?.outputs ?? []).some(y => y.url === x.url),
        ),
      ].filter(x => ['video', 'pdf', 'html'].includes(x.kind)),
    renders = () =>
      ((s.project?.description.extra as any)?.renders ?? []) as {
        res: string
        url: string
        stale: boolean
        bytes: number
      }[]
  onMount(() => {
    const close = (e: MouseEvent) => wrap && !wrap.contains(e.target as Node) && setOpen(false)
    document.addEventListener('mousedown', close)
    onCleanup(() => document.removeEventListener('mousedown', close))
  })
  const share = async () => {
    setSharing(true)
    try {
      const url = await s.share()
      if (url) await navigator.clipboard.writeText(url)
    } finally {
      setSharing(false)
    }
  }
  return (
    <span class="topbar-actions">
      <Show when={s.busy}>
        <button class="topbar-btn primary" onClick={() => void s.stop()}>
          Stop
        </button>
      </Show>
      <button
        class="topbar-btn"
        title="Publish and copy share link"
        disabled={sharing()}
        onClick={() => void share()}
      >
        <Link size={14} /> {s.project?.shareSlug ? 'Copy share link' : 'Share'}
      </button>
      <div class="export-wrap" ref={wrap}>
        <button class="topbar-btn export" onClick={() => setOpen(v => !v)}>
          <span
            class="export-fill"
            style={{ width: s.exportStatus?.running ? `${s.exportStatus.progress}%` : '0' }}
          />
          <span class="export-label">
            {s.exportStatus?.running
              ? `Rendering ${s.exportStatus.progress}%`
              : launch()
                ? 'Export MP4'
                : 'Download'}
          </span>
        </button>
        <Show when={open()}>
          <div class="export-menu">
            <Show
              when={launch()}
              fallback={
                <For each={outputs()}>
                  {o => (
                    <button
                      class="export-row"
                      onClick={() =>
                        s.download(
                          o.url,
                          `${s.project?.title ?? 'export'}.${o.kind === 'pdf' ? 'pdf' : o.kind === 'html' ? 'html' : 'mp4'}`,
                        )
                      }
                    >
                      <span class="export-row-main">
                        <span class="export-row-label">{o.label ?? o.kind.toUpperCase()}</span>
                        <span class="export-row-note">
                          {new Date(o.createdAt).toLocaleString()}
                        </span>
                      </span>
                      <span class="export-row-status">download</span>
                    </button>
                  )}
                </For>
              }
            >
              <For each={RES}>
                {r => {
                  const have = () => renders().find(x => x.res === r.res)
                  return (
                    <button
                      class="export-row"
                      disabled={!!s.exportStatus?.running}
                      onClick={() =>
                        have() && !have()!.stale
                          ? s.download(have()!.url, `${s.project?.title ?? 'export'}-${r.res}.mp4`)
                          : void s.exportVideo({ res: r.res })
                      }
                    >
                      <span class="export-row-main">
                        <span class="export-row-label">{r.res}</span>
                        <span class="export-row-note">{r.note}</span>
                      </span>
                      <span class="export-row-status">
                        {have() && !have()!.stale ? 'download' : 'render'}
                      </span>
                    </button>
                  )
                }}
              </For>
            </Show>
            <Show when={s.exportStatus?.running}>
              <button class="export-row" onClick={() => void s.cancelExport()}>
                Cancel render
              </button>
            </Show>
            <Show when={s.exportStatus?.stage === 'failed'}>
              <div class="export-error">{s.exportStatus?.error}</div>
            </Show>
          </div>
        </Show>
      </div>
    </span>
  )
}
export function StudioView(props: { projectId: string }) {
  const s = useProject(props.projectId),
    [view, setView] = createSignal<'preview' | 'files'>('preview'),
    [sidebar, setSidebar] = createSignal(
      typeof window === 'undefined' ? 440 : Math.min(520, Math.max(340, innerWidth * 0.3)),
    ),
    [tray, setTray] = createSignal(
      typeof window === 'undefined' ? 220 : Math.min(240, Math.max(180, innerHeight * 0.23)),
    )
  let feed: HTMLDivElement | undefined,
    side: HTMLElement | undefined,
    wrap: HTMLDivElement | undefined,
    stage: HTMLDivElement | undefined,
    followFeed = true,
    drag: { x: number; w: number } | null = null,
    trayDrag: { y: number; h: number } | null = null
  createEffect(() => {
    s.entries.reduce((n, e) => n + e.text.length, s.entries.length)
    queueMicrotask(() => {
      if (feed && followFeed) feed.scrollTop = feed.scrollHeight
    })
  })
  const stripKind = createMemo(() =>
    s.project?.description.slides
      ? 'slides'
      : (s.project?.description.scenes?.length ?? 0) > 0 ||
          s.project?.description.preview?.kind === 'html'
        ? 'scenes'
        : null,
  )
  const resizeTray = (height: number) =>
    setTray(Math.max(120, Math.min(height, Math.max(120, (stage?.clientHeight ?? 600) - 200))))
  onMount(() => {
    const observer = new ResizeObserver(() => resizeTray(tray()))
    if (stage) observer.observe(stage)
    onCleanup(() => observer.disconnect())
  })
  return (
    <div class="lv-studio">
      <Show when={!s.loadError} fallback={<div class="picker-empty">{s.loadError}</div>}>
        <div class="editor-wrap" ref={wrap} style={{ '--sidebar-w': `${sidebar()}px` }}>
          <header class="job-topbar job-topbar-split">
            <div class="topbar-split-left" style={{ width: `${sidebar()}px` }}>
              <div class="nav-crumb">
                <span class="editor-project">{s.project?.title ?? '…'}</span>
                <span class="project-kind">
                  {TITLES[s.project?.description.preview?.kind ?? ''] ?? 'Project'}
                </span>
                <span
                  class={`project-state ${s.busy ? 'working' : (s.project?.status ?? 'empty')}`}
                >
                  <i />{' '}
                  {s.busy
                    ? 'Working'
                    : s.project?.status
                      ? `${s.project.status[0].toUpperCase()}${s.project.status.slice(1)}`
                      : 'Empty'}
                </span>
              </div>
            </div>
            <div class="topbar-split-right">
              <div class="topbar-split-tabs">
                <button
                  aria-label="Preview"
                  class={`preview-pane-tab${view() === 'preview' ? ' is-active' : ''}`}
                  onClick={() => setView('preview')}
                >
                  <MonitorPlay size={15} />
                  <span>Preview</span>
                </button>
                <button
                  aria-label={`Files (${s.assets.length})`}
                  class={`preview-pane-tab${view() === 'files' ? ' is-active' : ''}`}
                  onClick={() => {
                    s.player.current?.pause?.()
                    setView('files')
                  }}
                >
                  <Files size={15} />
                  <span>Files</span>
                  <small>{s.assets.length}</small>
                </button>
              </div>
              <Actions store={s} />
            </div>
          </header>
          <div class="editor">
            <aside
              class={`edit-sidebar${s.busy ? ' is-working' : ''}`}
              ref={side}
              style={{ '--sidebar-w': `${sidebar()}px` }}
              aria-busy={s.busy}
            >
              <div
                class="feed"
                ref={feed}
                onScroll={event => {
                  const el = event.currentTarget
                  followFeed = el.scrollHeight - el.scrollTop - el.clientHeight < 64
                }}
              >
                <Show
                  when={s.entries.length}
                  fallback={
                    <div class="feed-empty">
                      Describe what you want, or ask for a change. Pick a scene or slide below, or
                      press <kbd>i</kbd> and click things in the preview.
                    </div>
                  }
                >
                  <Thread
                    entries={s.entries}
                    busy={s.busy}
                    onAnswer={s.send}
                    onEdit={entry => void s.rollback(entry)}
                  />
                </Show>
              </div>
              <Composer store={s} />
            </aside>
            <div
              class="resize-handle"
              role="separator"
              aria-label="Resize conversation"
              aria-orientation="vertical"
              tabIndex={0}
              onPointerDown={e => {
                drag = { x: e.clientX, w: sidebar() }
                e.currentTarget.setPointerCapture(e.pointerId)
              }}
              onPointerMove={e => {
                if (!drag) return
                const w = Math.min(
                  640,
                  (wrap?.clientWidth ?? innerWidth) * 0.48,
                  Math.max(320, drag.w + e.clientX - drag.x),
                )
                side?.style.setProperty('--sidebar-w', `${w}px`)
                wrap?.style.setProperty('--sidebar-w', `${w}px`)
                setSidebar(w)
              }}
              onPointerUp={() => (drag = null)}
              onPointerCancel={() => (drag = null)}
              onLostPointerCapture={() => (drag = null)}
            />
            <div class="editor-stage" ref={stage}>
              <div class="studio-preview-view" hidden={view() !== 'preview'}>
                <div class="player">
                  <div class="player-stage">
                    <Preview store={s} />
                  </div>
                </div>
                <Show when={stripKind()}>
                  <div
                    class="resize-handle-h"
                    role="separator"
                    aria-label="Resize timeline"
                    aria-orientation="horizontal"
                    aria-valuemin={120}
                    aria-valuemax={Math.max(120, (stage?.clientHeight ?? 600) - 200)}
                    aria-valuenow={Math.round(tray())}
                    tabIndex={0}
                    onKeyDown={event => {
                      if (!['ArrowUp', 'ArrowDown', 'Home', 'End'].includes(event.key)) return
                      event.preventDefault()
                      resizeTray(
                        event.key === 'Home'
                          ? 120
                          : event.key === 'End'
                            ? Infinity
                            : tray() + (event.key === 'ArrowUp' ? 24 : -24),
                      )
                    }}
                    onPointerDown={e => {
                      e.preventDefault()
                      e.currentTarget.focus()
                      trayDrag = {
                        y: e.clientY,
                        h:
                          e.currentTarget.nextElementSibling?.getBoundingClientRect().height ??
                          tray(),
                      }
                      e.currentTarget.setPointerCapture(e.pointerId)
                    }}
                    onPointerMove={e =>
                      trayDrag && resizeTray(trayDrag.h - (e.clientY - trayDrag.y))
                    }
                    onPointerUp={() => (trayDrag = null)}
                    onPointerCancel={() => (trayDrag = null)}
                    onLostPointerCapture={() => (trayDrag = null)}
                  />
                </Show>
                <div class="tray" style={stripKind() ? { height: `${tray()}px` } : undefined}>
                  <Switch
                    fallback={
                      <div class="timeline studio-empty-timeline">
                        <div class="timeline-header">
                          <h2>Timeline</h2>
                          <span class="timeline-meta">Scenes and slides appear here</span>
                        </div>
                      </div>
                    }
                  >
                    <Match when={stripKind() === 'slides'}>
                      <SlideStrip store={s} />
                    </Match>
                    <Match when={stripKind() === 'scenes'}>
                      <SceneStrip store={s} />
                    </Match>
                  </Switch>
                </div>
              </div>
              <Show when={view() === 'files'}>
                <div class="studio-files-view">
                  <AssetShelf store={s} />
                </div>
              </Show>
            </div>
          </div>
        </div>
      </Show>
    </div>
  )
}

// apps/studio-web/src/studio/StudioView.tsx
/**
 * The studio: preview on the left (the flow decides the renderer), the
 * agent's thread and the composer on the right, a scene/slide strip when
 * the flow has one. Everything the model does is visible; everything the
 * agent saves shows up in the preview.
 */
import { useEffect, useRef, useState } from 'react'
import { useNavigate } from 'react-router-dom'
import { Composer } from './Composer'
import { BrowserPreview } from './previews/BrowserPreview'
import { DeckPreview } from './previews/DeckPreview'
import { HtmlPreview } from './previews/HtmlPreview'
import { PdfPreview } from './previews/PdfPreview'
import { VideoPreview } from './previews/VideoPreview'
import { SceneStrip, SlideStrip } from './Strips'
import { Thread } from './Thread'
import { type ProjectStore, useProject } from './useProject'
import './studio.css'

/** What the project currently IS, read off the artifact rather than a flag. */
const ARTIFACT_TITLES: Record<string, string> = {
  html: 'Launch film',
  deck: 'Slide deck',
  video: 'Video',
  pdf: 'PDF',
  browser: 'Recording',
}

function BuildingStage({ busy, status, empty }: { busy: boolean; status: string; empty: string }) {
  return (
    <div className="building-stage">
      <div className="building-orbs">
        <span className="orb o1" />
        <span className="orb o2" />
        <span className="orb o3" />
      </div>
      <div className="building-frames">
        <span className="bframe" />
        <span className="bframe" />
        <span className="bframe" />
        <span className="bframe" />
        <span className="bframe" />
      </div>
      <div className="building-copy">
        {busy ? (
          <>
            <div className="building-title">
              <span className="spinner" /> Working
            </div>
            <div className="building-status">{status}</div>
          </>
        ) : (
          <>
            <div className="building-title">Nothing to preview yet</div>
            <div className="building-status">{empty}</div>
          </>
        )}
      </div>
    </div>
  )
}

function Preview({ store }: { store: ProjectStore }) {
  const s = store
  const preview = s.project?.description.preview ?? null
  const empty = s.project?.lastError
    ? `Last attempt failed: ${s.project.lastError}. Ask the agent to try again.`
    : 'Describe what you want below — the first result appears here as soon as it exists.'
  if (!preview) return <BuildingStage busy={s.busy} status={s.status} empty={empty} />
  if (preview.kind === 'html') {
    const src = s.mediaUrl(preview.url, s.videoVersion)
    return src ? <HtmlPreview store={s} src={src} /> : null
  }
  if (preview.kind === 'deck') {
    const src = s.mediaUrl(preview.url, s.videoVersion)
    return src ? <DeckPreview store={s} src={`${src}&studio=1`} /> : null
  }
  if (preview.kind === 'video') {
    const src = s.mediaUrl(preview.url, s.videoVersion)
    return src ? <VideoPreview store={s} src={src} /> : null
  }
  if (preview.kind === 'pdf') {
    const src = s.mediaUrl(preview.url, s.videoVersion)
    return src ? <PdfPreview store={s} src={src} /> : null
  }
  if (preview.kind === 'browser') return <BrowserPreview store={s} profileId={preview.profileId} />
  return null
}

const LAUNCH_RES = [
  { res: '720p', label: '720p', note: '1280 × 720 · quick share' },
  { res: '1080p', label: '1080p', note: '1920 × 1080 · standard' },
  { res: '4k', label: '4K', note: '3840 × 2160 · slow render' },
]

function ExportMenu({ store }: { store: ProjectStore }) {
  const s = store
  const [open, setOpen] = useState(false)
  const wrap = useRef<HTMLDivElement | null>(null)
  const st = s.exportStatus
  const rendering = !!st?.running
  const failed = st?.stage === 'failed' && !rendering
  // Resolution tiers belong to the launch engine, which is what an html preview is.
  const isLaunch = s.project?.description.preview?.kind === 'html'
  const outputs = s.project?.outputs ?? []
  const localOutputs = s.project?.description.outputs ?? []
  const renders = (s.project?.description.extra as any)?.renders as
    | Array<{ res: string; url: string; stale: boolean; bytes: number }>
    | undefined

  useEffect(() => {
    const onDoc = (e: MouseEvent) =>
      wrap.current && !wrap.current.contains(e.target as Node) && setOpen(false)
    document.addEventListener('mousedown', onDoc)
    return () => document.removeEventListener('mousedown', onDoc)
  }, [])

  const label = () => {
    if (st?.running) {
      if (st.stage === 'mixing') return 'Mixing audio…'
      if (st.stage === 'encoding') return 'Encoding…'
      if (st.stage === 'muxing') return 'Adding audio…'
      if (st.stage === 'uploading') return 'Uploading…'
      if (st.stage === 'capturing') return `Rendering ${st.res ?? ''} ${st.progress}%`
      return 'Starting render…'
    }
    if (failed) return 'Export failed'
    return isLaunch ? 'Export MP4' : 'Download'
  }

  const items = isLaunch
    ? LAUNCH_RES.map(o => {
        const have = renders?.find(r => r.res === o.res)
        const paid = s.project?.options.resolution ?? '1080p'
        const status =
          st?.running && st.res === o.res
            ? 'rendering…'
            : have && !have.stale
              ? `download · ${Math.round(have.bytes / 1e6)} MB`
              : have
                ? 'outdated · re-render'
                : 'render'
        return {
          key: o.res,
          label: `${o.label}${paid === o.res ? ' · included' : ''}`,
          note: o.note,
          status,
          onClick: () => void s.exportVideo({ res: o.res }),
        }
      })
    : [...outputs, ...localOutputs.filter(l => !outputs.some(o => o.url === l.url))]
        .filter(o => o.kind === 'video' || o.kind === 'pdf' || o.kind === 'html')
        .map(o => ({
          key: o.url,
          label: o.label ?? (o.kind === 'pdf' ? 'PDF' : o.kind === 'html' ? 'HTML' : 'Video'),
          note: new Date(o.createdAt).toLocaleString(),
          status: 'download',
          onClick: () => {
            const a = document.createElement('a')
            a.href = s.mediaUrl(o.url) ?? o.url
            a.download = `${s.project?.title ?? 'export'}.${o.kind === 'pdf' ? 'pdf' : o.kind === 'html' ? 'html' : 'mp4'}`
            a.target = '_blank'
            a.click()
          },
        }))

  const disabled = !s.project?.description.preview && items.length === 0
  return (
    <div className="export-wrap" ref={wrap}>
      <button
        className={`topbar-btn export ${failed ? 'failed' : ''} ${open ? 'open' : ''}`}
        disabled={disabled || (s.busy && !rendering && isLaunch)}
        title={failed ? (st?.error ?? '') : 'Download the result'}
        onClick={() => setOpen(v => !v)}
      >
        <span
          className="export-fill"
          style={{ width: rendering ? `${st?.progress ?? 0}%` : '0' }}
        />
        <span className="export-label">
          {rendering && <span className="spinner" />}
          {label()}
          <svg
            className="export-caret"
            viewBox="0 0 12 12"
            width="10"
            height="10"
            fill="currentColor"
          >
            <path d="M2 4l4 4 4-4z" />
          </svg>
        </span>
      </button>
      {open && (
        <div className="export-menu">
          {items.length === 0 && (
            <div className="export-row-note" style={{ padding: 10 }}>
              Nothing to download yet.
            </div>
          )}
          {items.map(it => (
            <button
              key={it.key}
              className="export-row"
              disabled={rendering}
              onClick={() => {
                it.onClick()
                setOpen(false)
              }}
            >
              <span className="export-row-main">
                <span className="export-row-label">{it.label}</span>
                <span className="export-row-note">{it.note}</span>
              </span>
              <span className="export-row-status">{it.status}</span>
            </button>
          ))}
          {rendering && (
            <button className="export-row" onClick={() => void s.cancelExport()}>
              <span className="export-row-label">Cancel render</span>
            </button>
          )}
          {failed && st?.error && <div className="export-error">{st.error}</div>}
        </div>
      )}
    </div>
  )
}

function Topbar({ store }: { store: ProjectStore }) {
  const s = store
  const navigate = useNavigate()
  const p = s.project
  const [shareUrl, setShareUrl] = useState<string | null>(
    p?.shareSlug && p.isPublic ? `${window.location.origin}/d/${p.shareSlug}` : null,
  )
  useEffect(
    () =>
      setShareUrl(p?.shareSlug && p.isPublic ? `${window.location.origin}/d/${p.shareSlug}` : null),
    [p?.shareSlug, p?.isPublic],
  )
  const hasOutput = (p?.outputs.length ?? 0) > 0
  return (
    <div className="job-topbar">
      <button className="topbar-btn" onClick={() => navigate('/projects')}>
        ← Projects
      </button>
      <div className="nav-crumb">
        <span className="editor-project" title={p?.name}>
          {p?.title ?? '…'}
        </span>
        <span className="status-pill" style={{ textTransform: 'none', letterSpacing: 0 }}>
          {ARTIFACT_TITLES[p?.description.preview?.kind ?? ''] ?? 'Project'}
        </span>
        <span
          className={`status-pill ${s.busy ? 'busy' : ''} ${!s.busy && (p?.description.preview || hasOutput) ? 'ready' : ''}`}
        >
          {s.busy ? (
            <>
              <span className="spinner" /> working
            </>
          ) : p?.description.preview || hasOutput ? (
            'ready'
          ) : p?.lastError ? (
            'failed'
          ) : (
            'empty'
          )}
        </span>
      </div>
      <span className="topbar-actions">
        {s.busy && (
          <button className="topbar-btn primary" onClick={() => void s.stop()}>
            Stop
          </button>
        )}
        <ExportMenu store={s} />
        {hasOutput && (
          <button
            className="topbar-btn"
            title={shareUrl ? 'Copy the public link' : 'Create a public link'}
            onClick={async () => {
              const url = shareUrl ?? (await s.share().catch(() => null))
              if (!url) return
              setShareUrl(url)
              await navigator.clipboard.writeText(url).catch(() => {})
              alert(`Public link copied:\n${url}`)
            }}
          >
            {shareUrl ? 'Copy link' : 'Share'}
          </button>
        )}
        <button
          className="topbar-btn danger"
          onClick={() => {
            if (p && confirm(`Delete "${p.title}" and everything in it?`))
              void s.remove().then(() => navigate('/projects'))
          }}
        >
          Delete
        </button>
      </span>
    </div>
  )
}

export function StudioView({ projectId }: { projectId: string }) {
  const s = useProject(projectId)
  const feedEl = useRef<HTMLDivElement | null>(null)
  const sidebarEl = useRef<HTMLElement | null>(null)
  const drag = useRef({ dragging: false, startX: 0, startW: 0, width: 420 })
  const streamLength = s.entries.reduce((n, e) => n + e.text.length, s.entries.length)
  useEffect(() => {
    queueMicrotask(() => {
      if (feedEl.current) feedEl.current.scrollTop = feedEl.current.scrollHeight
    })
  }, [streamLength])

  if (s.loadError) {
    return (
      <div className="lv-studio">
        <div className="picker-empty">{s.loadError}</div>
      </div>
    )
  }
  const desc = s.project?.description
  // The strip is how a timed artifact is selected in: slides for a deck, shots
  // for a launch film, narration beats for a video. A video with no beats (a
  // plain upload, an edit that never ran a transcript) has nothing to list, so
  // it gets no strip rather than an empty one.
  const strip = desc?.slides ? (
    <SlideStrip store={s} />
  ) : (desc?.scenes?.length ?? 0) > 0 || desc?.preview?.kind === 'html' ? (
    <SceneStrip store={s} />
  ) : null

  return (
    <div className="lv-studio">
      <div className="editor-wrap">
        <Topbar store={s} />
        <div className="editor">
          <div className="editor-stage">
            <div className="player">
              <div className="player-stage">
                <Preview store={s} />
              </div>
            </div>
            {strip}
          </div>
          <div
            className="resize-handle"
            onPointerDown={e => {
              drag.current = {
                ...drag.current,
                dragging: true,
                startX: e.clientX,
                startW: drag.current.width,
              }
              ;(e.target as HTMLElement).setPointerCapture(e.pointerId)
            }}
            onPointerMove={e => {
              if (!drag.current.dragging) return
              drag.current.width = Math.min(
                Math.max(drag.current.startW + (drag.current.startX - e.clientX), 320),
                720,
              )
              if (sidebarEl.current) sidebarEl.current.style.width = `${drag.current.width}px`
            }}
            onPointerUp={() => {
              drag.current.dragging = false
            }}
          />
          <aside
            className="edit-sidebar"
            ref={sidebarEl}
            style={{ width: `${drag.current.width}px` }}
          >
            <div className="feed-header">
              <h2>Agent</h2>
              {s.busy && (
                <span className="timeline-live" style={{ marginLeft: 'auto', fontSize: 11 }}>
                  {s.status}
                </span>
              )}
            </div>
            <div className="feed" ref={feedEl}>
              {s.entries.length > 0 ? (
                <Thread entries={s.entries} busy={s.busy} />
              ) : (
                <div className="feed-empty">
                  Describe what you want, or ask for a change. Pick a scene or slide below, or press{' '}
                  <kbd>i</kbd> and click things in the preview to reference them in your prompt.
                </div>
              )}
            </div>
            <Composer store={s} />
          </aside>
        </div>
      </div>
    </div>
  )
}
