// apps/web/src/solid/public/LandingFooter.tsx
import { A } from '@solidjs/router'
import { Instagram, Linkedin, Youtube } from 'lucide-solid'
import { For, type JSX, onMount } from 'solid-js'
import { DiscordIcon, PitchWordmark, XIcon } from './brand'
import '../../styles/landing-broadcast.css'

export interface Footer15Link {
  label: string
  href: string
  icon?: (props: { class?: string; size?: number }) => JSX.Element
}
export interface Footer15Column {
  title: string
  links: Footer15Link[]
}
export interface Footer15Props {
  logoIcon?: JSX.Element
  description?: string
  columns?: Footer15Column[]
}

export const SOCIALS: Footer15Link[] = [
  { label: 'Twitter', href: 'https://x.com/trypitchdotco', icon: XIcon },
  { label: 'Instagram', href: 'https://www.instagram.com/trypitch.co', icon: Instagram },
  {
    label: 'LinkedIn',
    href: 'https://www.linkedin.com/company/trypitchdotco/',
    icon: Linkedin,
  },
  { label: 'Discord', href: 'https://discord.gg/a4SBW36mD', icon: DiscordIcon },
  { label: 'YouTube', href: 'https://www.youtube.com/@trypitchdotco', icon: Youtube },
]
const columns: Footer15Column[] = [
  {
    title: 'Company',
    links: [
      { label: 'About Us', href: '/about' },
      { label: 'Blog', href: '/blog' },
      { label: 'Contact', href: 'mailto:support@trypitch.co' },
    ],
  },
  {
    title: 'Legal',
    links: [
      { label: 'Privacy Policy', href: '/privacy' },
      { label: 'Terms of Service', href: '/terms' },
    ],
  },
  {
    title: 'Product',
    links: [
      { label: 'Pricing', href: '/pricing' },
      { label: 'Docs', href: '/docs' },
      { label: 'API Reference', href: '/docs/api' },
    ],
  },
  { title: 'Social', links: SOCIALS },
]
const InternalOrExternal = (props: { link: Footer15Link }) =>
  props.link.href.startsWith('/') ? (
    <A
      href={props.link.href}
      class="inline-block text-xs leading-none font-light tracking-wide text-zinc-400 transition-colors duration-200 hover:text-white"
    >
      {props.link.label}
    </A>
  ) : (
    <a
      href={props.link.href}
      target={props.link.href.startsWith('http') ? '_blank' : undefined}
      rel={props.link.href.startsWith('http') ? 'noopener noreferrer' : undefined}
      class="inline-block text-xs leading-none font-light tracking-wide text-zinc-400 transition-colors duration-200 hover:text-white"
    >
      {props.link.label}
    </a>
  )

export function Footer15(props: Footer15Props) {
  let root!: HTMLElement
  onMount(() => {
    if (matchMedia('(prefers-reduced-motion: reduce)').matches) return
    const io = new IntersectionObserver(
      ([entry]) => {
        if (!entry.isIntersecting) return
        ;[...root.querySelectorAll<HTMLElement>('[data-footer-rise]')].forEach((el, i) =>
          el.animate(
            [
              { opacity: 0, transform: 'translateY(18px)', filter: 'blur(6px)' },
              { opacity: 1, transform: 'none', filter: 'blur(0)' },
            ],
            { duration: 600, delay: i * 70, easing: 'cubic-bezier(.2,.8,.2,1)', fill: 'both' },
          ),
        )
        io.disconnect()
      },
      { threshold: 0.1 },
    )
    io.observe(root)
  })
  const cols = () => props.columns ?? columns
  return (
    <footer
      ref={root}
      class="w-full overflow-hidden rounded-t-4xl bg-black text-white font-sans antialiased sm:rounded-t-[2.5rem] md:rounded-t-[3rem]"
    >
      <div class="px-6 pt-6 pb-2 sm:px-10 sm:pt-8 lg:px-14 lg:pt-10 xl:px-20">
        <div class="mx-auto flex max-w-[1440px] flex-col items-center justify-center gap-8 text-center">
          <div data-footer-rise class="flex shrink-0 flex-col items-center text-center gap-5">
            <div class="flex items-center justify-center w-full">
              <span class="shrink-0 text-white">
                {props.logoIcon ?? (
                  <PitchWordmark class="text-white" style={{ height: '40px', width: 'auto' }} />
                )}
              </span>
            </div>
            <p class="text-xs leading-relaxed font-light tracking-wide sm:whitespace-nowrap text-zinc-400">
              {props.description ??
                'The AI agent that turns your product URL into a cinematic pitch video in minutes.'}
            </p>
          </div>
          <nav
            aria-label="Footer navigation"
            class="grid w-full max-w-4xl grid-cols-2 sm:grid-cols-4 gap-x-12 gap-y-8"
          >
            <For each={cols()}>
              {column => (
                <div data-footer-rise class="text-center sm:text-left">
                  <h3 class="text-[10px] leading-none font-bold tracking-widest uppercase text-zinc-100">
                    {column.title}
                  </h3>
                  {column.title === 'Social' ? (
                    <div class="flex flex-row gap-4 justify-center sm:justify-start items-center mt-4 leading-none">
                      <For each={column.links}>
                        {link => (
                          <a
                            href={link.href}
                            target="_blank"
                            rel="noopener noreferrer"
                            class="inline-flex items-center justify-center text-white hover:text-zinc-300 transition-colors duration-200"
                            aria-label={link.label}
                          >
                            {link.icon?.({ class: 'size-3.5', size: 14 })}
                          </a>
                        )}
                      </For>
                    </div>
                  ) : (
                    <ul class="mt-3 flex flex-col gap-3">
                      <For each={column.links}>
                        {link => (
                          <li>
                            <InternalOrExternal link={link} />
                          </li>
                        )}
                      </For>
                    </ul>
                  )}
                </div>
              )}
            </For>
          </nav>
        </div>
      </div>
      <div class="mt-6 border-t border-zinc-900 px-6 py-4 sm:px-10 lg:px-14 xl:px-20">
        <div class="mx-auto flex max-w-[1440px] items-center justify-center text-center text-xs text-zinc-500">
          <p class="text-[10px] leading-none font-light tracking-widest uppercase text-zinc-500">
            © {new Date().getFullYear()} Pitch. All rights reserved.
          </p>
        </div>
      </div>
    </footer>
  )
}
export const LandingFooter = () => (
  <div class="lb-chrome flex w-full items-end">
    <Footer15 />
  </div>
)

// apps/web/src/components/LandingFooter.tsx
import { motion, type Variants } from 'framer-motion'
import type { ReactNode } from 'react'
import { FaInstagram, FaLinkedinIn, FaXTwitter } from 'react-icons/fa6'
import { Link } from 'react-router-dom'
import { PitchWordmark } from './PitchWordmark'

export interface Footer15Link {
  label: string
  href: string
  icon?: React.ComponentType<{ className?: string; size?: number }>
}

export interface Footer15Column {
  title: string
  links: Footer15Link[]
}

export interface Footer15Props {
  /** Custom logo mark element */
  logoIcon?: ReactNode
  /** Short brand description / tagline */
  description?: string
  /** Navigation columns */
  columns?: Footer15Column[]
}

const defaultColumns: Footer15Column[] = [
  {
    title: 'Company',
    links: [
      { label: 'About Us', href: '/about' },
      { label: 'Blog', href: '/blog' },
      { label: 'Contact', href: 'mailto:support@trypitch.co' },
    ],
  },
  {
    title: 'Legal',
    links: [
      { label: 'Privacy Policy', href: '/privacy' },
      { label: 'Terms of Service', href: '/terms' },
    ],
  },
  {
    title: 'Product',
    links: [{ label: 'Pricing', href: '/pricing' }],
  },
  {
    title: 'Social',
    links: [
      { label: 'Twitter', href: 'https://x.com/trypitchdotco', icon: FaXTwitter },
      { label: 'Instagram', href: 'https://www.instagram.com/trypitch.co', icon: FaInstagram },
      {
        label: 'LinkedIn',
        href: 'https://www.linkedin.com/company/trypitchdotco/',
        icon: FaLinkedinIn,
      },
    ],
  },
]

const staggerContainer: Variants = {
  hidden: { opacity: 0 },
  visible: {
    opacity: 1,
    transition: {
      staggerChildren: 0.09,
      delayChildren: 0.05,
    },
  },
}

const navStagger: Variants = {
  hidden: { opacity: 0 },
  visible: {
    opacity: 1,
    transition: {
      staggerChildren: 0.07,
      delayChildren: 0.02,
    },
  },
}

const riseItem: Variants = {
  hidden: { opacity: 0, y: 18, filter: 'blur(6px)' },
  visible: {
    opacity: 1,
    y: 0,
    filter: 'blur(0px)',
    transition: { type: 'spring', duration: 0.6, bounce: 0 },
  },
}

const linkStagger: Variants = {
  hidden: {},
  visible: { transition: { staggerChildren: 0.04 } },
}

const linkItem: Variants = {
  hidden: { opacity: 0, y: 5 },
  visible: {
    opacity: 1,
    y: 0,
    transition: { type: 'spring', duration: 0.4, bounce: 0 },
  },
}

export function Footer15({
  logoIcon,
  description = 'The AI agent that turns your product URL into a cinematic pitch video in minutes.',
  columns = defaultColumns,
}: Footer15Props) {
  return (
    <footer className="w-full overflow-hidden rounded-t-4xl bg-black text-white font-sans antialiased sm:rounded-t-[2.5rem] md:rounded-t-[3rem]">
      <motion.div
        variants={staggerContainer}
        initial="hidden"
        whileInView="visible"
        viewport={{ once: true, amount: 0.1 }}
        className="px-6 pt-6 pb-2 sm:px-10 sm:pt-8 lg:px-14 lg:pt-10 xl:px-20"
      >
        <div className="mx-auto flex max-w-[1440px] flex-col items-center justify-center gap-8 text-center">
          <motion.div
            variants={riseItem}
            className="flex shrink-0 flex-col items-center text-center gap-5"
          >
            <div className="flex items-center justify-center w-full">
              <span className="shrink-0 text-white">
                {logoIcon ?? (
                  <PitchWordmark className="text-white" style={{ height: '40px', width: 'auto' }} />
                )}
              </span>
            </div>

            <p className="text-xs leading-relaxed font-light tracking-wide sm:whitespace-nowrap text-zinc-400">
              {description}
            </p>
          </motion.div>

          <motion.nav
            variants={navStagger}
            aria-label="Footer navigation"
            className="grid w-full max-w-4xl grid-cols-2 sm:grid-cols-4 gap-x-12 gap-y-8"
          >
            {columns.map(col => (
              <motion.div key={col.title} variants={riseItem} className="text-center sm:text-left">
                <h3 className="text-[10px] leading-none font-bold tracking-widest uppercase text-zinc-100">
                  {col.title}
                </h3>
                {col.title === 'Social' ? (
                  <div className="flex flex-row gap-4 justify-center sm:justify-start items-center mt-4 leading-none">
                    {col.links.map(link => {
                      const Icon = link.icon
                      return (
                        <motion.a
                          key={link.label}
                          href={link.href}
                          variants={linkItem}
                          whileHover={{ scale: 1.15 }}
                          transition={{ type: 'spring', stiffness: 400, damping: 17 }}
                          target="_blank"
                          rel="noopener noreferrer"
                          className="inline-flex items-center justify-center text-white hover:text-zinc-300 transition-colors duration-200"
                          aria-label={link.label}
                        >
                          {Icon && <Icon className="size-3.5" />}
                        </motion.a>
                      )
                    })}
                  </div>
                ) : (
                  <motion.ul variants={linkStagger} className="mt-3 flex flex-col gap-3">
                    {col.links.map(link => (
                      <motion.li key={link.label} variants={linkItem}>
                        {link.href.startsWith('/') && !link.href.startsWith('//') ? (
                          <Link
                            to={link.href}
                            className="inline-block text-xs leading-none font-light tracking-wide text-zinc-400 transition-colors duration-200 hover:text-white"
                          >
                            {link.label}
                          </Link>
                        ) : (
                          <a
                            href={link.href}
                            className="inline-block text-xs leading-none font-light tracking-wide text-zinc-400 transition-colors duration-200 hover:text-white"
                            target={link.href.startsWith('http') ? '_blank' : undefined}
                            rel={link.href.startsWith('http') ? 'noopener noreferrer' : undefined}
                          >
                            {link.label}
                          </a>
                        )}
                      </motion.li>
                    ))}
                  </motion.ul>
                )}
              </motion.div>
            ))}
          </motion.nav>
        </div>
      </motion.div>

      {/* Copyright row */}
      <div className="mt-6 border-t border-zinc-900 px-6 py-4 sm:px-10 lg:px-14 xl:px-20">
        <div className="mx-auto flex max-w-[1440px] items-center justify-center text-center text-xs text-zinc-500">
          <p className="text-[10px] leading-none font-light tracking-widest uppercase text-zinc-500">
            © {new Date().getFullYear()} Pitch. All rights reserved.
          </p>
        </div>
      </div>
    </footer>
  )
}

export const LandingFooter = () => {
  return (
    <div className="flex w-full items-end">
      <Footer15 />
    </div>
  )
}
