// apps/web/src/components/Seo.tsx
import { useEffect } from 'react'
import {
  DEFAULT_DESCRIPTION,
  DEFAULT_OG_IMAGE,
  DEFAULT_TITLE,
  SITE_NAME,
  SITE_URL,
} from '../lib/seo'

interface SeoProps {
  title: string
  description: string
  /** Canonical path, e.g. "/blog/my-post". */
  path: string
  type?: 'website' | 'article'
  image?: string
  jsonLd?: Record<string, unknown> | Record<string, unknown>[]
}

const JSONLD_ATTR = 'data-seo-jsonld'

function upsertMeta(attr: 'name' | 'property', key: string, content: string) {
  let el = document.head.querySelector<HTMLMetaElement>(`meta[${attr}="${key}"]`)
  if (!el) {
    el = document.createElement('meta')
    el.setAttribute(attr, key)
    document.head.appendChild(el)
  }
  el.setAttribute('content', content)
}

function upsertCanonical(href: string) {
  let el = document.head.querySelector<HTMLLinkElement>('link[rel="canonical"]')
  if (!el) {
    el = document.createElement('link')
    el.setAttribute('rel', 'canonical')
    document.head.appendChild(el)
  }
  el.setAttribute('href', href)
}

/**
 * Per-route document head management (title, description, canonical, OG/Twitter,
 * optional JSON-LD). Restores the index.html defaults on unmount so navigating
 * back to a page without <Seo /> leaves sane tags.
 */
export function Seo({ title, description, path, type = 'website', image, jsonLd }: SeoProps) {
  useEffect(() => {
    const url = `${SITE_URL}${path}`
    const ogImage = image ?? DEFAULT_OG_IMAGE

    document.title = title
    upsertMeta('name', 'description', description)
    upsertMeta('property', 'og:title', title)
    upsertMeta('property', 'og:description', description)
    upsertMeta('property', 'og:url', url)
    upsertMeta('property', 'og:type', type)
    upsertMeta('property', 'og:site_name', SITE_NAME)
    upsertMeta('property', 'og:image', ogImage)
    upsertMeta('name', 'twitter:card', 'summary_large_image')
    upsertMeta('name', 'twitter:title', title)
    upsertMeta('name', 'twitter:description', description)
    upsertMeta('name', 'twitter:image', ogImage)
    upsertCanonical(url)

    const items = jsonLd ? (Array.isArray(jsonLd) ? jsonLd : [jsonLd]) : []
    const scripts: HTMLScriptElement[] = []
    for (const item of items) {
      const script = document.createElement('script')
      script.type = 'application/ld+json'
      script.setAttribute(JSONLD_ATTR, '')
      script.textContent = JSON.stringify(item)
      document.head.appendChild(script)
      scripts.push(script)
    }

    return () => {
      document.title = DEFAULT_TITLE
      upsertMeta('name', 'description', DEFAULT_DESCRIPTION)
      upsertCanonical(`${SITE_URL}/`)
      for (const script of scripts) script.remove()
    }
  }, [title, description, path, type, image, jsonLd])

  return null
}

// apps/web/src/solid/core/Seo.tsx
import { createEffect, onCleanup } from 'solid-js'

export interface SeoProps {
  title: string
  description: string
  path: string
  image?: string
  /** Page-level schema.org JSON-LD; the site-wide graph lives in index.html. */
  jsonLd?: Record<string, unknown>
}

export const SITE_URL = (import.meta.env.VITE_SITE_URL ?? 'https://trypitch.co').replace(/\/$/, '')

function upsertMeta(selector: string, attributes: Record<string, string>): HTMLMetaElement {
  const existing = document.head.querySelector<HTMLMetaElement>(selector)
  const element = existing ?? document.createElement('meta')
  for (const [name, value] of Object.entries(attributes)) element.setAttribute(name, value)
  if (!existing) document.head.append(element)
  return element
}

export function Seo(props: SeoProps) {
  createEffect(() => {
    const previousTitle = document.title
    document.title = props.title
    const url = `${SITE_URL}${props.path.startsWith('/') ? props.path : `/${props.path}`}`
    const canonical =
      document.head.querySelector<HTMLLinkElement>('link[rel="canonical"]') ??
      document.createElement('link')
    canonical.rel = 'canonical'
    canonical.href = url
    if (!canonical.isConnected) document.head.append(canonical)

    upsertMeta('meta[name="description"]', { name: 'description', content: props.description })
    upsertMeta('meta[property="og:title"]', { property: 'og:title', content: props.title })
    upsertMeta('meta[property="og:description"]', {
      property: 'og:description',
      content: props.description,
    })
    upsertMeta('meta[property="og:url"]', { property: 'og:url', content: url })
    upsertMeta('meta[name="twitter:card"]', {
      name: 'twitter:card',
      content: props.image ? 'summary_large_image' : 'summary',
    })
    if (props.image) {
      upsertMeta('meta[property="og:image"]', { property: 'og:image', content: props.image })
      upsertMeta('meta[name="twitter:image"]', { name: 'twitter:image', content: props.image })
    }

    // A prerendered page already carries its JSON-LD; replace it, never stack a copy.
    for (const stale of document.head.querySelectorAll('script[data-page]')) stale.remove()
    let ld: HTMLScriptElement | undefined
    if (props.jsonLd) {
      ld = document.createElement('script')
      ld.type = 'application/ld+json'
      ld.dataset.page = ''
      ld.textContent = JSON.stringify(props.jsonLd)
      document.head.append(ld)
    }

    onCleanup(() => {
      document.title = previousTitle
      ld?.remove()
    })
  })
  return null
}
